### ISSUE TITLE
CPU/Memory stats not updating

### ISSUE THREAD

**Issue by shaunol** [DockStation/dockstation#101]
Hi there, 

I've just downloaded dockstation and connected to my docker hosts no problem but most container stats aren't working. Only network sent/received is working. CPU/Memory is not working. When I run 'docker stats' I can see CPU/Memory is updating no problem. 

My host is running Windows Server 2016 docker 17.06.2-ee-6 - my client machine is Windows 10 docker 17.09.1-ce running the latest Dockstation.

I've tried ticking on/off "new version" setting on the dockstation connection but this doesn't change anything. 

Here's a screenshot of the CPU/Memory stats stuck on '0' alongside the 'docker stats' output of the host showing that no container is sitting on 0 memory:

![image](https://user-images.githubusercontent.com/228220/33964999-4537683c-e0bf-11e7-9a23-e840fdad4104.png)

Thanks!

**Comment by igor-lemon** [comment]
Hi @shaunol. I'll check it. But I have one question.
I see that you're using a remote connection and into Terminal you have many containers but the app shows only one. Please make a screenshot of your connection settings.

**Comment by igor-lemon** [comment]
Sorry. I see that you filtered containers. 
Other containers also don't have any CPU/MEM/... params?

**Comment by shaunol** [comment]
No problem, that's correct, I was filtered on the container I was most interested in at the time, here's the unfiltered list:

![image](https://user-images.githubusercontent.com/228220/33965384-87aaac1e-e0c0-11e7-8145-89ce8beaafd6.png)

Every container is stuck on 0 CPU/Mem, eg:

![image](https://user-images.githubusercontent.com/228220/33965419-a29ce820-e0c0-11e7-82c9-a0ae40824ec2.png)

Here are the connection settings:

![image](https://user-images.githubusercontent.com/228220/33965460-cf12d4fa-e0c0-11e7-814f-1e627f311d6b.png)

I've tried this against 2 separate hosts (both running Server 2016 with docker 17.06.2-ee-6) with the same issue. (wcontainers1/wcontainers2). The connection parameters are the same as I'm passing into the docker stats command: eg `docker -H=wcontainers1:2375`

**Comment by shaunol** [comment]
Just noticed there's a full stats output window:

![image](https://user-images.githubusercontent.com/228220/33965517-14146be0-e0c1-11e7-9507-f35bbda9cd3a.png)

**Comment by igor-lemon** [comment]
Ok. Thanks. 
Do you use `Docker for Windows`?

**Comment by shaunol** [comment]
Yes, my Windows 10 client machine (with dockstation) is running docker for Windows, downloaded frome: https://docs.docker.com/docker-for-windows/install/

![image](https://user-images.githubusercontent.com/228220/33965822-335a00cc-e0c2-11e7-8034-0c1a9c477eb2.png)

The Server 2016 container hosts are using Docker EE from here https://docs.docker.com/engine/installation/windows/docker-ee/ (Server 2016 hosts are running LTSB *not* 1709)

**Comment by igor-lemon** [comment]
Ok. Thank. We'll check your issue on a Windows machine.

**Comment by shaunol** [comment]
Sounds great, I appreciate the fast reply, let me know if you need any other debug/diagnostics along the way

**Comment by shaunol** [comment]
@igor-lemon sorry for not mentioning this before  but I also have 2x Linux container hosts running Ubuntu 16.04.3 LTS with docker 17.09.0-ce - I just tested against these hosts and the stats are working correctly. (same Windows 10 client & dockstation install).

![image](https://user-images.githubusercontent.com/228220/33967950-826ce398-e0ca-11e7-97d2-863f99651bf1.png)

![image](https://user-images.githubusercontent.com/228220/33967958-8c02e18c-e0ca-11e7-943f-a08e78f2e959.png)

**Comment by igor-lemon** [comment]
Hm. We couldn't reproduce your issue on our Windows machines...

**Comment by igor-lemon** [comment]
@shaunol I have good news. We reproduced the bug. It was a bug in external lib. It bug has fixed. In the next 1.4 version of the app, it will be fixed too.

**Comment by shaunol** [comment]
@igor-lemon that is really great news, looking forward to trying 1.4 - and again, I really appreciate the fast response time!

**Comment by VincentDumas** [comment]
Hi there, I can see the same issue. I am running Dockstation v1.4.1 on windows 10, Version 2.0.0.3 
With Docker (31259) Build: 8858db3
