### ISSUE TITLE
[ macOS ] 'SET PATH' dialog doesn't allow to create a new directory

### ISSUE THREAD

**Issue by cig0** [DockStation/dockstation#103]
Hi,

When creating a new project, there's no way to also create a new directory(s) from within the shown dialog:

![screen shot 2017-12-16 at 21 02 06-compressed](https://user-images.githubusercontent.com/394089/34075424-628310a2-e2a5-11e7-9ee1-4dbd373cd5ca.png)

**Comment by igor-lemon** [comment]
Hi @cig0. Sure, because it's "Select Dialog". It's a feature of macOS.

**Comment by cig0** [comment]
It would be handy, though, to have the ability to create a new directory when starting to work on a project from scratch. Sometimes you might want to create it from the CLI while others from the GUI depending on the specific workflow of the moment.
