### ISSUE TITLE
Stop auto startup

### ISSUE THREAD

**Issue by sonicviz** [DockStation/dockstation#105]
It's really annoying to start Dockstation up and have multiple projects auto start.
Please make auto start an option and not the default.

**Comment by igor-lemon** [comment]
Hi @sonicviz 
Sorry, what? We don't  start automatically anything.

**Comment by sonicviz** [comment]
Sometimes when I start Dockstation a number of the projects start up automatically. I can't see any setting that control that, and haven't fully determined what the trigger condition is.

**Comment by igor-lemon** [comment]
Nope. The app doesn't start anything and can't do it. Because we didn't implement that :D
You can see a running project because you have all running project containers.
All running containers of project equal running project.

**Comment by sonicviz** [comment]
Something is triggering multiple projects to start. I'm not imagining it.

**Comment by igor-lemon** [comment]
Can you shoot this?

**Comment by sonicviz** [comment]
You mean video?

**Comment by igor-lemon** [comment]
Yep

**Comment by sonicviz** [comment]
I'll see what I can do. I'm still trying to determine the trigger.

**Comment by igor-lemon** [comment]
Ok.
You have intrigued me.

**Comment by sonicviz** [comment]
Trust me, I'm not making it up. There's something that's causing a bunch of projects to start when I open Dockstation sometimes. They only partially start too, a bunch of containers in them don't start while some do. The only consistent thing I've noticed is it's the same group of projects that seem to be doing it.

**Comment by igor-lemon** [comment]
So, I can't say anything at the moment because you're first with that issue. 
Try to find some trigger how to reproduce it.

**Comment by sonicviz** [comment]
I think I know what the issue is. 
It seems related to Docker restarting. This is supposed to shut all containers down but it seems it leaves some containers started (I don't know why).
When I start Dockstation after one of these restarts it looks like it has autostarted a bunch of projects but they are incompletely started. Weird.

So I agree, I don't think it's a Dockstation issue. Apologies for the confusion. Great tool!

**Comment by igor-lemon** [comment]
Hm. Did you try to do it via Terminal (start/stop/restart). Does issue repeat?

**Comment by pashist** [comment]
@sonicviz check please restart policy in your docker compose config file. Looks like you have `restart: always` for some services.
More info https://docs.docker.com/compose/compose-file/compose-file-v2/#restart

**Comment by sonicviz** [comment]
Thanks. I was thinking it might be this.

**Comment by sonicviz** [comment]
>>@sonicviz check please restart policy in your docker compose config file. Looks like you have restart: always for some services.

No, that's not it. I removed all restart statements, and default is no.

When restarting docker (for eg: changing CPU/RAM) I'm still getting certain containers automatically starting up and as a result in Dockstation shows the projects partially started.

**Comment by goldenpipes** [comment]
@sonicviz did you ever solve this? i would like to have a certain project start when dockstation starts.  since that doesn't seem possible what was causing your containers to start?

**Comment by sonicviz** [comment]
Sorry, never did solve it.
