### ISSUE TITLE
multiple docker-compose files in the same folder

### ISSUE THREAD

**Issue by BorisDaich** [DockStation/dockstation#106]
[we](url) got 2 logical levels of containers 
docker-compose.yml  -- infrastructure containers 
and 
docker-compose.services.yml  --- application containers 

we run it as 
docker-compose -f docker-compose.yml -f docker-compose.services.yml up -d 
but when debugging we run only the  docker-compose.yml  and the rest are started from IDE

I would like to have support for this scenario

generally let us pick particular  docker-compose.yml file as a project
of pick several *.yml files as a single project

**Comment by igor-lemon** [comment]
Hi @BorisDaich 
Right now you can add additional YML config and work with it.
![image](https://user-images.githubusercontent.com/14764799/34839949-76a694a4-f714-11e7-8508-5566eb1c9209.png)

But for your case, I think that need to make some Run/Debug configurator like JetBrain IDE configurator. 
![image](https://user-images.githubusercontent.com/14764799/34871414-9e83fe32-f79e-11e7-9e7d-fe850a347a6b.png)
