### ISSUE TITLE
Error when closing the Dockstation window and reopening (macOS)

### ISSUE THREAD

**Issue by GasimGasimzada** [DockStation/dockstation#109]
- macOS version: 10.13.3
- Dockstation version: v1.3.0

	Uncaught Exception:
	Error: Object has been destroyed
	    at App.<anonymous> (/Applications/DockStation.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:1:1)
	    at emitTwo (events.js:106:13)
	    at App.emit (events.js:194:7)

I believe the error is there because macOS has window close an application close as separate functions in Electron.

**Comment by igor-lemon** [comment]
Hi @GasimGasimzada 

How often can you reproduce the error, per each close app event?

**Comment by GasimGasimzada** [comment]
Sorry, I did not see your response a month ago. The error is still there. 100% of the time.

**Comment by igor-lemon** [comment]
Hi. Did you update up to v1.4?

**Comment by GasimGasimzada** [comment]
Yes, I just did and the error is still there. When I close the window, the app stays open; and when I try to open it, the window does not get created and I get an error.

**Comment by igor-lemon** [comment]
Fixed.

**Comment by GasimGasimzada** [comment]
Thank you! Closing the window no reopens it properly. However, now CTRL+W is not closing the window. Is that the intended behavior?

**Comment by igor-lemon** [comment]
The closing window via CMD+W was a mistake because the app has only 1 window and you should have only 2 options - Minimize (CMD + M) or Quit (CMD +Q) :)
