### ISSUE TITLE
Dockstation version unknown

### ISSUE THREAD

**Issue by ghost** [DockStation/dockstation#113]
Where in the application can I find the version? I have installed 1.4.1 and now it suggest I download it again because it thinks it is an update. How can I check if the update actually worked?
This may be a feature request for the 'About Dockstation' menu :)

**Comment by igor-lemon** [comment]
Hi. 
DockStation - About
When did you update the app? Because we had a bit trouble 10 days ago, we published not correct v1.4.1 version and it was published during in 15mins. After we closed the wrong release and published after 1-day correct version of the app.

**Comment by Thijxx** [comment]
Not sure if you repeat my question or you think there is a menu DockStation-About, either way, there is no About menu.
I downloaded the 1.4.1 version on the 6th of April

**Comment by igor-lemon** [comment]
![image](https://user-images.githubusercontent.com/14764799/38578505-c449b3a6-3d0c-11e8-9d22-0553b6a9e425.png)

**Comment by igor-lemon** [comment]
Do you have access to GitHub without any proxy? Because for version info we're making a GitHub request.

**Comment by Thijxx** [comment]
The entire menu bar is missing for me.. running Arch Linux with Gnome. 
You probably do not support Arch ;) but it is at least clear what I'm missing now, thanks!

**Comment by igor-lemon** [comment]
I think that we support all platforms, for Arch we built AppImage. But tested it only on Ubuntu and Debian. So, thanks for feedback, I'll check your issue and will try to fix it.
