### ISSUE TITLE
Improve restart logic of a container

### ISSUE THREAD

**Issue by danfarewell** [DockStation/dockstation#114]
Hey,

currently if you are in the containers tab and for example a container crashes, the container status (green circle) stays green. This indicates the container is running while its not. This is only refreshed once you switch to another tab and switch back to containers. 

A big problem for me is, that if a container is crashed and the green circle is available indicating the container is running and you are clicking on restart, an error will occur telling me the container restart failed.

There are some solutions for this problem:
- Container view automatically refreshes on x time
- Container restart button checks the state of the container before doing anything (If container is still running - restart, if container is not running, simply restart)

Best regards

**Comment by igor-lemon** [comment]
Hi @danfarewell 

I'll check Docker sends some signals after container crash or not. I'll write you results. 
I'll be grateful if you share an image or a Dockerfile for replicate container crashing.
