### ISSUE TITLE
Dockstation will not connect to Docker for Windows (18.03) using Windows containers

### ISSUE THREAD

**Issue by dougis** [DockStation/dockstation#120]
Running Docker for Windows Version 18.03.1-ce-win65 (17513) and using Windows Containers I get the following error when trying to start a project

[stdout]: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

**Comment by igor-lemon** [comment]
Hi @dougis Thanks for the issue. We'll check your case.

**Comment by igor-lemon** [comment]
We reproduced your problem. It's trouble of Docker Compose. We hope Docker will able fix that near future.

Let's try to make it (it helped to resolve your trouble on our side)
https://github.com/docker/for-win/issues/268
