### ISSUE TITLE
Stats Monitor shows different information than the docker stats command

### ISSUE THREAD

**Issue by cbdejavu** [DockStation/dockstation#122]
Not sure if I just am not understanding something or if you app is monitoring something additionally than what the docker stats command monitors.  I'm noticing that your stats monitor are different (sometime considerably than the docker stats command).

For example memory is typically not even close.  I'll have a container that the docker stats command says is using 289mb of ram and your stats monitor says it is using 1.39gb of ram.  I guess if it is working correctly then what are you measuring that makes your numbers so much different.

**Comment by igor-lemon** [comment]
Hi @cbdejavu Thanks for the issue. Can you say what is version of Docker you're using?

**Comment by cbdejavu** [comment]
Here's the info from the docker version command:
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:38 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:45 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by cbdejavu** [comment]
Also for note, the dockstation was installed using the ubuntu software center app and is version 1.4.1

**Comment by igor-lemon** [comment]
Yep. I checked. It's very interesting, but it's the bug of Docker.
An example
![image](https://user-images.githubusercontent.com/14764799/41506910-82a15be0-722f-11e8-8c8e-039b87e3c92e.png)

Values on screenshot are different, but we use Docker API. I called 
`curl --unix-socket /var/run/docker.sock "http:/v1.24/containers/bf7d9e22d8f3/stats?stdout=1"`

And I have next data:
```js
{"read":"2018-06-17T10:05:15.245401953Z","preread":"2018-06-17T10:05:14.239553672Z","pids_stats":{"current":38},"blkio_stats":{"io_service_bytes_recursive":[{"major":8,"minor":0,"op":"Read","value":122744832},{"major":8,"minor":0,"op":"Write","value":21188608},{"major":8,"minor":0,"op":"Sync","value":0},{"major":8,"minor":0,"op":"Async","value":143933440},{"major":8,"minor":0,"op":"Total","value":143933440}],"io_serviced_recursive":[{"major":8,"minor":0,"op":"Read","value":3379},{"major":8,"minor":0,"op":"Write","value":56},{"major":8,"minor":0,"op":"Sync","value":0},{"major":8,"minor":0,"op":"Async","value":3435},{"major":8,"minor":0,"op":"Total","value":3435}],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]},"num_procs":0,"storage_stats":{},"cpu_stats":{"cpu_usage":{"total_usage":30308612667,"percpu_usage":[8191916818,6891004021,8008310623,7217381205],"usage_in_kernelmode":2700000000,"usage_in_usermode":21870000000},"system_cpu_usage":35116340000000,"online_cpus":4,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"precpu_stats":{"cpu_usage":{"total_usage":30307261677,"percpu_usage":[8191655599,6890933370,8007291503,7217381205],"usage_in_kernelmode":2700000000,"usage_in_usermode":21870000000},"system_cpu_usage":35112310000000,"online_cpus":4,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{"usage":596320256,"max_usage":597049344,"stats":{"active_anon":352874496,"active_file":42319872,"cache":189681664,"dirty":8192,"hierarchical_memory_limit":9223372036854771712,"hierarchical_memsw_limit":9223372036854771712,"inactive_anon":47181824,"inactive_file":147361792,"mapped_file":23511040,"pgfault":111158,"pgmajfault":208,"pgpgin":159626,"pgpgout":15647,"rss":400056320,"rss_huge":0,"total_active_anon":352874496,"total_active_file":42319872,"total_cache":189681664,"total_dirty":8192,"total_inactive_anon":47181824,"total_inactive_file":147361792,"total_mapped_file":23511040,"total_pgfault":111158,"total_pgmajfault":208,"total_pgpgin":159626,"total_pgpgout":15647,"total_rss":400056320,"total_rss_huge":0,"total_unevictable":0,"total_writeback":0,"unevictable":0,"writeback":0},"limit":2095771648},"name":"/opencv_jenkins_1","id":"bf7d9e22d8f37d454fb46b5ce13745de53ae544677a2b32d98e68740e1dd83c4","networks":{"eth0":{"rx_bytes":3512036,"rx_packets":2589,"rx_errors":0,"rx_dropped":0,"tx_bytes":107322,"tx_packets":1929,"tx_errors":0,"tx_dropped":0}}}
```

memory_stats -> usage = 596320256 bytes = 568.7 MB
