### ISSUE TITLE
Mixing logs between different containers

### ISSUE THREAD

**Issue by camohob** [DockStation/dockstation#132]
When i have 2 or more containers from same image - logs are mixed between different containers and different projects. After refresh log - all is ok.
![image](https://user-images.githubusercontent.com/7923965/44656476-a84b5a80-aa01-11e8-9165-517bd03a31b7.png)
on screenshot you can see 'node_1' container log in project which not contain this container.

**Comment by igor-lemon** [comment]
Hi @camohob. Thanks for the issue. I'll check your case and write results.

**Comment by camohob** [comment]
Hi @igor-lemon, new details: this problem is not related to the same images. When I just run the dockstation (if the projects have already started earlier) - everything is fine, but after restarting any project - the logs are mixed between projects and containers.

**Comment by igor-lemon** [comment]
Hi @camohob So, we tried to reproduce your issue and couldn't do it. :(
I wanna find a reason of the problem. Can you record video with your issue?
Need to 
1) Show logs before project restart
2) After
3) Show logs from some other project
4) Show container logs from a terminal `docker logs CONTAINER_ID/CONTAINER_NAME`

**Comment by camohob** [comment]
Hi @igor-lemon, I record [video](https://youtu.be/kXHCECaHD-Q). As you can see - the problem also appears when switching between projects.

**Comment by igor-lemon** [comment]
I apologize for the long answer. Ok, thanks for the video. We'll check this case.

**Comment by igor-lemon** [comment]
Hi @camohob. We've good news, we found and fixed the bug. Fixes will be able in the v1.5

**Comment by camohob** [comment]
> Hi @camohob. We've good news, we found and fixed the bug. Fixes will be able in the v1.5

The problem still remain...

**Comment by igor-lemon** [comment]
It's strange because we fixed this. 
So, I'll recheck this case.
