### ISSUE TITLE
White screen on schema page

### ISSUE THREAD

**Issue by MetaiR** [DockStation/dockstation#133]
if there is a problem with the network, after going to the schema page, the application's window turns to the white and everything (buttons, tabs, even window management buttons like minimize and close button) are disappeared.

**Comment by igor-lemon** [comment]
Hi @MetaiR. I can't reproduce your issue on my side. Give me pls more info: OS, version of the app.

**Comment by MetaiR** [comment]
OS: manjaro, windows 10
the version of app: 1.4.1
I am living in Iran and when the proxy or vpn on my machine is off this happens

**Comment by MetaiR** [comment]
I assume it happens when the (docker) server returns status code 403
@igor-lemon

**Comment by igor-lemon** [comment]
So it's interesting... How can I reproduce 403 error?

**Comment by MetaiR** [comment]
u can use a simple web service or edit os net configuration or add it to ur router blacklist I suppose @igor-lemon

**Comment by MetaiR** [comment]
@igor-lemon 
Any solution?

**Comment by MetaiR** [comment]
@igor-lemon 
![deepin-screen-recorder_desktop_20180906182130](https://user-images.githubusercontent.com/7807264/45161971-35f92800-b202-11e8-8c49-5e864ff220d4.gif)

**Comment by igor-lemon** [comment]
Ok. Thanks for the video. 👍 
Tomorrow I'll try to reproduce it again and find a reason of trouble.

**Comment by MetaiR** [comment]
good to hear that,
with and without a vpn I saw a json with `recommended` and `repos` keys
@igor-lemon

**Comment by igor-lemon** [comment]
So, it's ok. Can you open without VPN this page? (You should see JSON object too)
https://hub.docker.com/v2/search/repositories/?query=ubuntu

**Comment by MetaiR** [comment]
@igor-lemon 
no, I faced 403 error page without VPN

**Comment by igor-lemon** [comment]
Awesome! So, we fixed the bug. The fixes will be available in the next 1.5 release.

**Comment by MetaiR** [comment]
@igor-lemon wow very excited to see it, when it'll be released?

**Comment by igor-lemon** [comment]
I can't say you the exact date, because we work on DockStation after main job and we don't have much time. I hope we'll publish next release next month because we're also making some other features.

**Comment by igor-lemon** [comment]
Not sure... :)

**Comment by MetaiR** [comment]
@igor-lemon notify me if there is anything I can help with

**Comment by igor-lemon** [comment]
ok
