### ISSUE TITLE
Where is container files?

### ISSUE THREAD

**Issue by lilleindi** [DockStation/dockstation#134]
I installed Jira. And now i want to access the files in the container. How do i do that?

The reason i want to access them is to change the hostname. It change ip after restart. 
Is that because i should use the hostname of the container instead of the ip?

Best Regards

**Comment by igor-lemon** [comment]
Hi @lilleindi. Sorry for the long answer. You can pass local dir into a container. 
![image](https://user-images.githubusercontent.com/14764799/46272391-8e012100-c559-11e8-9e6e-907f18e5b269.png)

If you want to use hostname you can do it  via "Host setting"
![image](https://user-images.githubusercontent.com/14764799/46272450-bee15600-c559-11e8-8722-73dd5f5e87a6.png)
