### ISSUE TITLE
Docker Event:Init Error

### ISSUE THREAD

**Issue by peterwkc** [DockStation/dockstation#135]
When i try to run Dockstation, it prompt out this error. 

![dockstation init error](https://user-images.githubusercontent.com/3906501/45214807-0b74a100-b2ce-11e8-990d-f95d402e3056.png)

**Comment by igor-lemon** [comment]
Hi @peterwkc. Did you run Docker?

**Comment by igor-lemon** [comment]
I don't have an answer

**Comment by roblox34** [comment]
> Hi @peterwkc. Did you run Docker?

no?
