### ISSUE TITLE
No documentation on how to connect to remote docker host

### ISSUE THREAD

**Issue by adrianocr** [DockStation/dockstation#136]
I have docker running on a home server and I'm trying to manage it from another machine using dockstation. But when I try to connect to it via SSH I get "socket hung up". The SSH connection is fine, I'm connected via the terminal right now. 

But I cannot get dockstation to connect using the same exact SSH connection.

**Comment by igor-lemon** [comment]
Hi @adrianocr Sorry for the long answer.

We don't have any documentation. I hope we'll change this in near future :)
So. 
1) Let's go to Containers
2) Click on the edit connection button
![image](https://user-images.githubusercontent.com/14764799/46272540-2bf4eb80-c55a-11e8-84f3-b29d0ea836f1.png)

3) Click "Add button"
4) Choose the type of connection (I recommend use SSH, it is more flexible and fast)
5) Input all fields.
6) Close the modal. Choose your connection and connect to remote server.

**Comment by alexlii1971** [comment]
oh... God....
I use dockstation for two years, but just find it support manage remote server....

**Comment by SHI-ZP** [comment]
Port would be 22 if you are using the SSH approach.
