### ISSUE TITLE
Not Able to Connect Remote Docker Hosts

### ISSUE THREAD

**Issue by shubhamgupta514** [DockStation/dockstation#139]
Hi Team,

Could please share the steps for connecting remote docker hosts.

Thanks,
Shubham Gupta

**Comment by igor-lemon** [comment]
Hi @shubhamgupta514. Sorry for the long answer.
You made duplicate
https://github.com/DockStation/dockstation/issues/136

I want to record short video tutorials about how to work with the app. 
So, I close this issue, let's go to the #136 issue.
