### ISSUE TITLE
new version release date

### ISSUE THREAD

**Issue by MetaiR** [DockStation/dockstation#144]
it's been a long time since the last release and there are many fixes that done for the new version.
so when can we see a new version do you think?

**Comment by MetaiR** [comment]
there are just two more days left, I am so excited, hope u can release on time

**Comment by igor-lemon** [comment]
Hi @MetaiR, have news - found some bugs in the Windows version. Fixing. :)

**Comment by MetaiR** [comment]
😢

**Comment by MetaiR** [comment]
so when do you think we can have new version?

**Comment by igor-lemon** [comment]
We should fix the last bug https://github.com/DockStation/dockstation/issues/132 and will release.

**Comment by avdmatamoros** [comment]
Hey, thanks for such a great app. Is there any news on the new version release date? I'm looking forward to the improvements and bugfixes (specially the windows one for the new docker)

**Comment by igor-lemon** [comment]
Hi @MetaiR 
Thanks for the feedback.
So, we need to fix the latest bug #149 and will publish the new release.
I hope we finish this week.

**Comment by MetaiR** [comment]
wow, it is a very good news. whish bests for u guys

**Comment by MetaiR** [comment]
@igor-lemon did u make it?

**Comment by MetaiR** [comment]
@igor-lemon 
can't u release a new version and fix that issue for the next release?
because as far as I know there are many fixes are done for this release already which we really need them

**Comment by igor-lemon** [comment]
Hi @MetaiR 
Sure. The #149 was fixed. But we need a few days for preparing docs, screenshots, need to buy a new apple dev license, update the site, and make some other stuff...

**Comment by MetaiR** [comment]
@igor-lemon 
Hi, is there any progress?

**Comment by igor-lemon** [comment]
The app is ready and tested, we have the last problem with the building of the app on Linux and Windows.
We updated many libs and right now have few problems with this.
I know I promise it many times but we need a bit time to fix this and we'll release the app.

**Comment by MetaiR** [comment]
@igor-lemon did u make it through?

**Comment by igor-lemon** [comment]
Hi @MetaiR So, I didn't write anything because I can't make a good EST.
I have good news. We fixed all bugs, added some new features, and the app is ready now. For publishing the new version, I need to write Changelog and update the site.

**Comment by MetaiR** [comment]
recently I have to work with docker a lot, I really wish ur new version has been released :cry:

**Comment by avdmatamoros** [comment]
I'm also looking forward to the new version. If there are still things that need to be worked on, would it be possible to try out a beta in the meantime?

**Comment by ccharlton** [comment]
Hungry for a new release. Yum!

(FYI, the two tickets referenced are both resolved.)

**Comment by MetaiR** [comment]
@ccharlton yeah they are, and we have to wait for the new version, that's why I refer them here

**Comment by MetaiR** [comment]
btw, I could talk to Igor, and there is hope that he has time for doing some of the prerequire things on monday

**Comment by ccharlton** [comment]
Why isn't any of the progress tracked in GH?

**Comment by polarathene** [comment]
@ccharlton It's closed-source. 

They could still keep progress tracked with issues and milestones or a single issue with checklist, but for whatever reason don't afaik?

**Comment by ADSapozhnikov** [comment]
Any updates on this?)

**Comment by gcastillo** [comment]
![image](https://user-images.githubusercontent.com/569497/55128490-5d99da00-50d9-11e9-82c0-c4f6fca8018d.png)

**Comment by igor-lemon** [comment]
Need to wait just a few days
![image](https://user-images.githubusercontent.com/14764799/55174416-731d0b80-518e-11e9-8cce-73186bc40b29.png)

**Comment by MetaiR** [comment]
any progresses?

**Comment by igor-lemon** [comment]
@MetaiR Yep. I'll write you :)

**Comment by igor-lemon** [comment]
The v1.5 is available. Thanks for waiting :D

**Comment by MetaiR** [comment]
happy new version.... :1st_place_medal:
