### ISSUE TITLE
Client update problem

### ISSUE THREAD

**Issue by MatiGdn** [DockStation/dockstation#145]
Hi Team, 
I have just started DockStation on a Windows 10 System and installed Docker for Windows. 
Now DockStation don't want to deplay containers. 
It is telling me: 
[stdout]: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer Version

How can i upgrade my Client on Windows? 
Do you know what is causing this Problem? 

Thank you in Advance & br
Mati
![issue_dockstation](https://user-images.githubusercontent.com/44367703/47293965-f6e53180-d60b-11e8-9e21-a236a9c8a8d4.jpg)

**Comment by igor-lemon** [comment]
Hi @MatiGdn 
Duplicated https://github.com/DockStation/dockstation/issues/120

Let me know if it solution doesn't resolve your problem.

**Comment by MatiGdn** [comment]
Hi Igor,

great ist working 😊. Thank you. But now it causes the next Problem and I didn’t find a solution on GitHub.

Error when I try to pull the nginx Image:
No matching manifest for unknown in the manifest list entries
Child process exited with Code 1

[cid:image003.png@01D46AC5.940F9DE0]

Thank you in Advance & br
Matthias

________________________________
Von: Igor Kozlovsky <notifications@github.com>
Gesendet: Monday, October 22, 2018 8:50:33 PM
An: DockStation/dockstation
Cc: MatiGdn; Mention
Betreff: Re: [DockStation/dockstation] Client update problem (#145)


Hi @MatiGdn<https://github.com/MatiGdn>
Duplicated #120<https://github.com/DockStation/dockstation/issues/120>

Let me know if it solution doesn't resolve your problem.

**Comment by igor-lemon** [comment]
Let's try
1) Right click Docker instance
2) Go to Settings
3) Daemon
4) Advanced
5) Set the "experimental": true
6) Restart Docker

**Comment by MatiGdn** [comment]
Great it works Thank you very much

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Igor Kozlovsky <notifications@github.com>
Gesendet: Tuesday, October 23, 2018 11:45:43 AM
An: DockStation/dockstation
Cc: MatiGdn; Mention
Betreff: Re: [DockStation/dockstation] Client update problem (#145)


Let's try

  1.  Right click Docker instance
  2.  Go to Settings
  3.  Daemon
  4.  Advanced
  5.  Set the "experimental": true
  6.  Restart Docker
