### ISSUE TITLE
App under windows loading more then 30 minutes.

### ISSUE THREAD

**Issue by boskiv** [DockStation/dockstation#147]
How I can check whats going on ?
I have install docker-machine and create default one.
Install app and run. After it (under my VM in Parallels) it show me loading screen and nothing more. It take more than 30 minutes.
I have 4 cpu and 4 gig ram for this VM.

![screenshot 2018-10-23 at 12 57 59 pm](https://user-images.githubusercontent.com/1939783/47352784-52262b00-d6c3-11e8-83f2-9be2745629ac.png)
![screenshot 2018-10-23 at 12 57 49 pm](https://user-images.githubusercontent.com/1939783/47352785-52bec180-d6c3-11e8-9b4c-8d55119de969.png)

**Comment by igor-lemon** [comment]
Hm. It's very strange. Did you change the general settings in the app (Set Docker Machine with )?
![image](https://user-images.githubusercontent.com/14764799/47353092-1475d200-d6c4-11e8-9b1f-7e636a08d851.png)

**Comment by boskiv** [comment]
No, It's fresh install, so I cant configure anything.

**Comment by igor-lemon** [comment]
Ok. Disable the Docker Machine (off VM). After need to relaunch the app. You should see the screen with error
![image](https://user-images.githubusercontent.com/14764799/47354985-e0e97680-d6c8-11e8-8d37-07e9f2713489.png)

Go to

1) Preferences
2) Docker
3) Select `Docker Machine`
4) Select `VMWare Fusion` driver
5) Relaunch the app or click on the `Projects` tab

**Comment by bakeiro** [comment]
Same here, win 10 pro, using hyper V fresh installation, just open dockstation and I can only see a loading screen

**Comment by igor-lemon** [comment]
Ok, I'll try to find some Windows machine for check your issue.

**Comment by boskiv** [comment]
I dont have fusion I have VirtualBox, sorry for miss VM- Virtual Machine not VMWare

**Comment by boskiv** [comment]
Is there some logfile to see whats happend and provide it to you?

**Comment by boskiv** [comment]
You advise helps. Now I created docker-machine from App, connected. But when I create a project ad add simple mysql image, i have an error same as https://github.com/DockStation/dockstation/issues/146

**Comment by bakeiro** [comment]
After a reboot now it's working in my pc, don't know how, but it works ahhah

**Comment by igor-lemon** [comment]
lol, I'll use this case
1) Reboot the PC and check again
2) ...
3) ...
