### ISSUE TITLE
(Windows) Won't connect to Docker Machine

### ISSUE THREAD

**Issue by STaRDoGG** [DockStation/dockstation#161]
Just installed the latest version of DS on Win 10 x64 running latest VirtualBox (_Hype-V causes BSOD on boot when it's enabled_) with a 'default' vm already created, and started.

In the following screenshot, I show that I've already started the 'default' machine, started the portainer container, the vbox headless .exe's are all running, and then started DS, and it just doesn't connect.

[Screenshot](https://i.imgur.com/1H6Rz6J.png)

Any ideas?

**Comment by igor-lemon** [comment]
Hi @STaRDoGG 
Did you click on "Init Docker Machine Automatically" button?
If you're using some custom virtual machine name go to the app settings and set needed params
![image](https://user-images.githubusercontent.com/14764799/52025855-003d3e80-2517-11e9-800f-ae622d706a1c.png)

**Comment by STaRDoGG** [comment]
Still having the same issue with the latest v1.5.1.

![image](https://user-images.githubusercontent.com/1524526/56423158-762c8880-6270-11e9-8928-6d57d304ed5e.png)

Is the devault vm supposed to be stopped before running DS, and not already running?

**Comment by Master64k** [comment]
I do have this issue as well.

Any updates on this?
