### ISSUE TITLE
Metrics section message is not in english

### ISSUE THREAD

**Issue by kmejka** [DockStation/dockstation#164]
The message in the UI about sending metrics is... it only tries to be in english. I had to read it three times before I understood it:
![image](https://user-images.githubusercontent.com/6838588/52120605-18978100-261d-11e9-9e13-768bf59709ef.png)

The correct message would be something like this:

>We're not recommending disabling this option, because with these metrics, we're able to make our application even better

or 

>We don't recommend disabling this option, because these metrics enable us to improve our application

**Comment by igor-lemon** [comment]
Hi @kmejka

Thank you for your comment!
Unfortunately, we have some grammar mistakes, we'll try to correct them.
