### ISSUE TITLE
Is dockstation a fork of Kitematic? 

### ISSUE THREAD

**Issue by kitingChris** [DockStation/dockstation#165]
I realized the app looks very similar.

You even copied the annoying left sided system buttons (which I originally wanted suggest to be able to move via settings).

Is that why you do not want to release the source code? 

But you know that the sources of an electron app can be extracted from the debian package do you?

**Comment by igor-lemon** [comment]
No. The app is not forked.
What? We made own UI/UX. Look Ant Design library for close your speculation.

We don't want to publish code because we don't do it now. 

You can extract JS file from any ASAR package but I don't understand what you want to see in obfuscated code.
