### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by CMYanko** [DockStation/dockstation#167]
I'm not complaining, just curious not having seen any coding activity in 2 yrs and a release that is coming up on its birthday. I've really think the thing is damn near perfect except for the tiny terminal font.

**Comment by igor-lemon** [comment]
Hi @CMYanko. Nope, the project is alive. But we don't have much time for working on this project. We have big plans and we'll try to reborn the project.
The last release was 29 Mar. 2018, it almost 1 year, not 2 :D
The next v1.5 release is compiled and done, but I still can't complete writing Terms and Conditions and update site.

**Comment by MetaiR** [comment]
@CMYanko #144

**Comment by ccharlton** [comment]
Close ticket. Clone repo. Code more. Let's do this! 🐞

**Comment by MM-Psiiirus** [comment]
@ccharlton you can't just clone it and "code more" there are no source files within this repo...But maybe its a good idea to go open source to spread this great product even more?!  @igor-lemon

**Comment by ccharlton** [comment]
OMG, you're right. The source is missing entirely. I thought it was hiding in a work branch, but no, this GH project is merely a marketing & downloads outlet for this "project". And, technically the project info/site does not mention the project is open sourced. Disappointing.

**Comment by shumer** [comment]
Agreed that this is can be a good idea, and ready to help with development.

**Comment by hoaivan** [comment]
Can't wait for the release!

**Comment by igor-lemon** [comment]
The v1.5 is available. Thanks for waiting :D
