### ISSUE TITLE
osascripts not allowed to send keystroke

### ISSUE THREAD

**Issue by nondualit** [DockStation/dockstation#175]
When executing command I get an error "osascripts not allowed to send keystroke"
No matter what I do. I cant find anything on fixing this. Can someone please help?

**Comment by igor-lemon** [comment]
Hi @nondualit 
I need more info about how to reproduce it.

**Comment by nondualit** [comment]
![image](https://user-images.githubusercontent.com/19951027/55891257-8a0f2500-5bb4-11e9-8e3e-fb0fb612ac8d.png)
![image](https://user-images.githubusercontent.com/19951027/55891355-b034c500-5bb4-11e9-8c58-5238cdeab899.png)

**Comment by nondualit** [comment]
Every application where the terminal is needed i get this error when pressing on exec

**Comment by igor-lemon** [comment]
![image](https://user-images.githubusercontent.com/14764799/55891548-6ac8c580-5bbd-11e9-8931-5ff1e3615beb.png)

**Comment by igor-lemon** [comment]
@nondualit Is it solved your issue?

**Comment by nondualit** [comment]
thanks Igor this solved thia issue
