### ISSUE TITLE
containers tab display is slow since 1.5.0

### ISSUE THREAD

**Issue by domotruc** [DockStation/dockstation#176]
Hi,
First, thanks for DockStation ! :smile:
Since version 1.5.0, the display of the _Containers_ tab is quiet long and takes about 5s:

   * When being on another tab and clicking on the _Containers_ tab;
   * When being on the _Containers_ tab and selecting another container

I have 6 containers.

**Comment by igor-lemon** [comment]
Hi @domotruc 
It's sad. I've seen it before. But before 1.5 release, we checked this and didn't find anything. 
So. Today I want to release 1.5.1 where we improved the performance of logs view, I hope it fixes your issue. 
Anyway, we'll fix this.

**Comment by igor-lemon** [comment]
Hi @domotruc. Let's check your issue on 1.5.1 version

**Comment by domotruc** [comment]
Hi @igor-lemon,
I just installed version 1.5.1 and the issue is solved. Good job !
Thanks a lot
