### ISSUE TITLE
Update process displays Javascript error when updating to v1.5.1

### ISSUE THREAD

**Issue by ccharlton** [DockStation/dockstation#178]
Saw a dialogue window with a "Cannot read property 'removeAllListeners' of null".

<img width="532" alt="Screen Shot 2019-04-15 at 2 59 32 PM" src="https://user-images.githubusercontent.com/263843/56168256-6d496780-5f8f-11e9-933a-2c69d5483999.png">

**Comment by igor-lemon** [comment]
Hi @ccharlton  How to reproduce it ?

**Comment by igor-lemon** [comment]
@ccharlton ping...

**Comment by ccharlton** [comment]
Sorry for my reply delay. I was updating to the latest version at that time, just downloaded the DMG and that prompt came up. Didn't come up before.
