### ISSUE TITLE
Won't quit with cmd-Q

### ISSUE THREAD

**Issue by snoblenet** [DockStation/dockstation#19]
I've installed Dockstation on two Macs.

On both of them, it won't quit with cmd-Q or selecting Quit from the menu.

**Comment by igor-lemon** [comment]
Hi @snobleney
Yep. You're right. We'll fix it in next release.
Thank you.

**Comment by bit0rez** [comment]
I`m sorry, but i tried close DockStation by Ctrl-Q on linux and DockStation was crashed. Window become white and processes stay alive.

I tried this on DockStation v1.2.2 on Ubuntu Linux 16.04 LTS.

**Comment by igor-lemon** [comment]
@bit0rez We couldn't reproduce your problem. Can you give more information what did you do before? Like as: Go to Containers, connect to remote server, stop containers, quit.

**Comment by igor-lemon** [comment]
@bit0rez Found a reason. We'll fix it. Thanks for issue.

**Comment by igor-lemon** [comment]
@bit0rez fixed. v1.2.3
