### ISSUE TITLE
Docker Events Init Error with remote docker host

### ISSUE THREAD

**Issue by Maxiride** [DockStation/dockstation#191]
I have a Raspberry Pi 3 running docker and docker-compose. For a while, I've been using Portainer but I wanted to change GUI and found DockStation promising.

On my remote host (the Raspberry runs into my LAN), I've enabled docker API on port 2375:

    $ cat /etc/systemd/system/docker.service.d/options.conf
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -H unix:// -H tcp://0.0.0.0:2375

DockStation can successfully connect to the host, however, this init error is shown. On the machine I'm connecting from there is no Docker (and I don't want to install it either). Do I need to change something else on the docker host or is something else needed on _my_ computer?

It was my understanding that with DockStaion I could manage my remote docker installation without having docker installed on the client.

![image](https://user-images.githubusercontent.com/3630857/59679018-1732b380-91ce-11e9-9c52-10307157a9d3.png)

![image](https://user-images.githubusercontent.com/3630857/59679000-0d10b500-91ce-11e9-8698-452df8a13fce.png)

**Comment by igor-lemon** [comment]
Hi @Maxiride 
For working with remote containers you don't need to install Docker at the local machine.
So, if you have a remote Docker machine just create a correct connection. 
![image](https://user-images.githubusercontent.com/14764799/59679700-39313380-91d8-11e9-82c4-066c0d1dd19a.png)

If you can connect to your Raspberry via SSH you try to connect to Docker via SSH
![image](https://user-images.githubusercontent.com/14764799/59679781-6d0c5900-91d8-11e9-99b6-7db5f004e4de.png)

**Comment by Maxiride** [comment]
I wrongly used the normal port over the SSH connection. Thanks for help.
