### ISSUE TITLE
 docstation failed to attach docker event listener connect ENOENT //./pipe/docker_engine

### ISSUE THREAD

**Issue by shalevy1** [DockStation/dockstation#206]
docstation failed to attach docker event listener connect ENOENT //./pipe/docker_engine

![Snap 2019-08-12 at 21 44 31](https://user-images.githubusercontent.com/23245639/62915760-78987e00-bd4a-11e9-9706-07fc1ba8909e.png)

Use docker for Windows

![Snap 2019-08-12 at 21 45 49](https://user-images.githubusercontent.com/23245639/62915803-9b2a9700-bd4a-11e9-980c-bb8b4e6b7c91.png)

**Comment by igor-lemon** [comment]
Hi @shalevy1 . Did you run Docker?

**Comment by shalevy1** [comment]
Operator error :( you are right, I didn't install/run Docker
The error message can be improved; closing issue
