### ISSUE TITLE
Feature: Export to docker-compose.yml

### ISSUE THREAD

**Issue by ttyS15** [DockStation/dockstation#21]

**Comment by igor-lemon** [comment]
Hi @ttyS15.
What do you mean? DockStation generates native docker-compose.yml

**Comment by ttyS15** [comment]
Yaeh! Thanks! Already seen. Sorry for noise!

**Comment by ttyS15** [comment]
You create very good product! Thank you!

**Comment by igor-lemon** [comment]
Thanks. We have many ideas for help and make work with docker easier. I think that we'll publish on the next week a big update with new awesome features. Stay with us. :)

**Comment by ttyS15** [comment]
Thanks! With pleasure! :)

Алексей Манаев
