### ISSUE TITLE
dockstation.io is down

### ISSUE THREAD

**Issue by theblackhole** [DockStation/dockstation#219]
Hello,
The title says it all https://www.isitdownrightnow.com/dockstation.io.html

**Comment by igor-lemon** [comment]
Hi @theblackhole Thanks for the issue! DigitalOcean stable down our nodes 1-2 times per month :(
Rebooted.

**Comment by theblackhole** [comment]
Thanks! If you want, you can use a monitoring tool like updown.io or uptimerobot.com to receive notifications (email, slack, etc...) when your website is down. It's easy and quick to setup ;)

**Comment by igor-lemon** [comment]
Yes, I use monitoring, but today I was unavailable and couldn't see messages. 
Your issue was first what I checked. :)
