### ISSUE TITLE
(macOS) OPENSSL_internal:DECODE_ERROR

### ISSUE THREAD

**Issue by markwylde** [DockStation/dockstation#226]
I'm not sure of the exact reasons why but when I tried to use dockstation my certificate was rejected with the following error:

```
OPENSSL_internal:DECODE_ERROR
```

To solve this I had to convert my certificate using the following command:

```bash
cd ~/.ssh
ssh-keygen -f id_rsa -m pem -p
```

Can we add this to the documentation or do this automatically?

**Comment by davimello28** [comment]
Same problem in Debian. Thanks for the solution.
