### ISSUE TITLE
No clipboard on OS X

### ISSUE THREAD

**Issue by zippanto** [DockStation/dockstation#231]
It seems there's no clipboard functionality at all in the OS X client.

**Comment by igor-lemon** [comment]
Hi @zippanto. Do you want to copy logs?

**Comment by zippanto** [comment]
Yes mainly, but should be possible in any parts of the application where it's possible to highlight text

**Comment by igor-lemon** [comment]
So, it's really strange because my friends and I checked this and on macOS copying works well.
What is your macOS and DockStation versions?

**Comment by zippanto** [comment]
hi @igor-lemon apologies not sure what was going on here. I just tried again and it's working now.
