### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by SolidRhino** [DockStation/dockstation#274]
The last release of this project was almost over 1 year ago. Is this project still active, or is there an alternative for this project.

**Comment by azumukupoe** [comment]
> The latest version: v1.5.1
>Released: 15 Apr. 2019

2 years

**Comment by igor-lemon** [comment]
Yep, 2 years. I think so, but need to understand that my friend left the project, and I just don't have the opportunity to work on the project full time as it was before, just a few hours per week.

**Comment by eshirvana** [comment]
then why not make the project open source and let people contribute to it.

**Comment by patrykorwat** [comment]
@igor-lemon Considering the Docker move to make Docker Desktop paid for large companies, can you publish the source code?

**Comment by malko** [comment]
We are now in april 2022, still no new release, it is understandable projects take time. Isn't it time for the project to go opensource instead or letting it dying like this. This is a useful tool it's really sad to see it dying like that.

**Comment by eshirvana** [comment]
for people who come here , here is the app I'm using for a long time and It's great : 
https://github.com/portainer/portainer
