### ISSUE TITLE
Firebase connection timeout

### ISSUE THREAD

**Issue by MiladMohebnia** [DockStation/dockstation#283]
Firebase not connecting well on my ISP and for the first connection (like login as guest or login with google) application triggers error of network problem (like timeout ..

**Comment by igor-lemon** [comment]
Hi! Where are you from? Do you have some firebase access problems, can you open https://firebase.google.com/?

**Comment by MiladMohebnia** [comment]
Hi! I'm from Iran.

firebase:


403. That’s an error.

Your client does not have permission to get URL / from this server. That’s all we know.

**Comment by MiladMohebnia** [comment]
firebase result:

**Comment by igor-lemon** [comment]
Oh, I had the same issues from Iran, your country under sanctions. I can just propose you use VPN. What about Docker Hub, is it blocked for you too?

**Comment by MiladMohebnia** [comment]
yep

**Comment by igor-lemon** [comment]
It's sad. But so far I can only propose you use VPN
