### ISSUE TITLE
Show relations

### ISSUE THREAD

**Issue by igor-lemon** [DockStation/dockstation#32]
Draw relation lines for `depends_on` option.

**Comment by sujunmin** [comment]
Hope this feature can be implemented at the SCHEME GUI.

**Comment by igor-lemon** [comment]
It released more the one year ago :)
Works on `depends_on` and `links` params.

**Comment by sujunmin** [comment]
Yes, I know the params can do that, and hope use SCHEME GUI (like drag and drop or something else) to achieve this options.

**Comment by igor-lemon** [comment]
So, the `links` option is not required because now all services links between each other by default.
About `depends_on`, I don't promise you that we'll implement it because now we have more priority features but we'll think about it. Thanks!
