### ISSUE TITLE
Is dockstation abandoned?

### ISSUE THREAD

**Issue by Luxvao** [DockStation/dockstation#330]
The last update was in 2019. Does anyone have any info? I asked on the website (the contact thing) and they didn't respond.

**Comment by igor-lemon** [comment]
I didn't receive any emails, the mail provider wants money for mail service providing.

About updates, I don't know. I don't have the motivation to do anything more.
I asked people to help test a new release and only a couple of people responded to the request but none really helped.
I don't see any reasons to spend my own time free and get nothing in return. Don't even get help testing the new release.

If you want updates I can propose using some other OpenSource solutions.

**Comment by Luxvao** [comment]
Alright. Thanks for clarifying it. I get what you're saying. I wish you the best :)

**Comment by neoacevedo** [comment]
Good, this repo then should be marked as read-only. A bad news for this nice open source app and I understand the situation.

**Comment by dmiales** [comment]
Так бездарно убить проект. Автор одновременно не хочет продолжать разработку, но при этом не выкладывает код в опенсурс для дальнейшего развития. 
Даже сайт перестал поддерживать....
