### ISSUE TITLE
Providers are not amused

### ISSUE THREAD

**Issue by jhintringer** [DockStation/dockstation#334]
Its very likely, that DockStation is the reason, why my provider shutdown my server and blocked my IP, because its showing up, that DockStation is scanning their infrastructure to find open Ports.

How exactly do DockStation find the running Containers? Is there some kind of Scanning of Networks?

If so, it can help me get unblocked.
Thanks

**Comment by igor-lemon** [comment]
DockStation is only powered by the Docker API, no port scans have ever been and are not there.
