### ISSUE TITLE
Docker Machine support

### ISSUE THREAD

**Issue by krainboltgreene** [DockStation/dockstation#34]
When I start the application I get the failwhale, because dockerstation doesn't know about my docker machine virtual machine.

**Comment by igor-lemon** [comment]
@krainboltgreene Right now we support only native Docker for Linux, Docker for Mac and Docker for Windows. We'll add docker machine support in the next release.

**Comment by krainboltgreene** [comment]
Awesome!!!

**Comment by igor-lemon** [comment]
Released into v1.3
