### ISSUE TITLE
Run application without Docker

### ISSUE THREAD

**Issue by igor-lemon** [DockStation/dockstation#35]
Don't throw general errors if user doesn't have Docker and Docker Compose for possibility to use application for managing only remote containers.

**Comment by hip3ri0n** [comment]
Yep. Also i wanted to create a remote container, that could be possible?

**Comment by igor-lemon** [comment]
@hip3ri0n It's possible but in the next release will be supported only local Docker Machines (based on VBox & Hyper-V drivers). We have plans to cover all Docker Machine drivers and make the analog of "Projects" for all instances (local Docker, remote Docker, local Docker Machine, remote Docker Machine).

**Comment by igor-lemon** [comment]
Released into v1.3
