### ISSUE TITLE
Readd project bug

### ISSUE THREAD

**Issue by brunogoossens** [DockStation/dockstation#38]
After removing a project and unchecked all boxes from the modal. I wanted to add it again with the same name and the same folder but it doesn't gets added to the list of project anymore. No error occurs.

**Comment by igor-lemon** [comment]
@brunogoossens 
1) What is a version of app?
2) OS

Is exists inside your directory docker-compose.yml? 
Did you change permissions of a directory or docker-compose.yml after delete project?

**Comment by brunogoossens** [comment]
dockstation: v1.2.1
OS: macOS v10.12.3

I didn't change any permissions.
The word "exists" is not present in my docker-compose.yml.

**Comment by igor-lemon** [comment]
I mean compose file inside project directory.
Strange that I can't reproduce your bug.

Can you write step by step what did you do?

**Comment by brunogoossens** [comment]
I can't reproduce the bug with an other project but the bug is still existing with this 1 project.
![bug](https://user-images.githubusercontent.com/1636664/27483430-a63d806c-5825-11e7-9af4-3b9805db84db.gif)

**Comment by brunogoossens** [comment]
Ok, i added the project with an other docker-compose.yml file and it worked. Reverted the original code and now getting the error "docker-compose file not valid". Would be nice to get the error message when adding the project.

When I use the docker-compose file form the command line, it works.

**Comment by igor-lemon** [comment]
Huh...
Please, provide me your docker-compose.yml
I reproduced the bug if I have not valid docker-compose.yml

**Comment by brunogoossens** [comment]
`version: '3'
services:
  php:
    build: php
    networks:
      - main
    links:
      - mongo
    networks:
      - main
    volumes:
      - app:/app
  mongo:
    build: mongo
    networks:
      - main
  nginx:
    build: nginx
    links:
      - php
    depends_on:
      - php
    networks:
      - main
    volumes:
      - app:/app
    ports:
        - "3001:80"
volumes:
  app:

networks:
  main:`

**Comment by brunogoossens** [comment]
```
    networks:
      - main
```
This is the part inside the service where he returns invalid format

**Comment by igor-lemon** [comment]
Yep. Strange that application doesn't show an error alert. I remember that we made it, but maybe something went wrong. We'll fix that.

Huh. We'll check the docker-compose validator too.

Thank you for the issue.

**Comment by brunogoossens** [comment]
Ok, thx for the support. I like the app! Is it going to be open source?

**Comment by igor-lemon** [comment]
@brunogoossens There's a possibility. I think that it will be known soon. :)

**Comment by igor-lemon** [comment]
fixed v1.2.2

**Comment by brunogoossens** [comment]
tested my case and it works! thx

**Comment by igor-lemon** [comment]
@brunogoossens Awesome :)
