### ISSUE TITLE
ubuntu 16 installation

### ISSUE THREAD

**Issue by Dmitry1987** [DockStation/dockstation#4]
Hi, 
want to report that I had to install those:

apt-get install libindicator7 libappindicator1

before was able to "dpkg -i" the dockstation deb file.
maybe it's worth to somehow package all needed dependencies with the installer if it's possible... though I doubt it is.

**Comment by DockStation** [comment]
@pashist try to install via terminal

**Comment by fturiot** [comment]
Hello problem
I install and i have error docker-compose --version error

**Comment by igor-lemon** [comment]
@fturiot I don't understand. Do you have an error in application?
Minimal version for correct working is Docker Compose v1.6.0+
Try to install/update
https://docs.docker.com/compose/install/

If you'll have the same problem please let's me know.
