### ISSUE TITLE
Create Project: Selecting path on windows results in javascript like error message in form

### ISSUE THREAD

**Issue by airtonix** [DockStation/dockstation#40]
![image](https://user-images.githubusercontent.com/61225/27777833-86816004-5ff5-11e7-8774-1913547fe6c4.png)

**Comment by igor-lemon** [comment]
@airtonix What is version of app, version of Windows ?

**Comment by igor-lemon** [comment]
Doh. Found a bug. Immediately fix. Thank you for the issue.

**Comment by igor-lemon** [comment]
@airtonix fixed. v1.2.4
