### ISSUE TITLE
how do I link containers through the gui?

### ISSUE THREAD

**Issue by VisualBean** [DockStation/dockstation#41]

**Comment by igor-lemon** [comment]
@VisualBean DockStation works with projects based on Docker Compose and all containers from the same project links between themselves by default.
If you usually work with Docker via `docker run ...` you have 3 ways
1) If you know Docker Compose you can manually create config file (by default all containers will be link between themselves from compose v2). 
2) You can create project via Parser
![image](https://user-images.githubusercontent.com/14764799/27881527-a56bdd9a-61d1-11e7-87da-0e3d92fe28d2.png)
3) You can create project via Scheme
![image](https://user-images.githubusercontent.com/14764799/27881573-de3249e8-61d1-11e7-968c-976c1bf7aeb2.png)

**Comment by igor-lemon** [comment]
@VisualBean Is the issue still relevant?

**Comment by VisualBean** [comment]
Great!  - the reason I was asking, was because I was trying to figure out how to link a mysql container with a wordpress container -
But for that I think i need to use docker compose - is this correct?

**Comment by igor-lemon** [comment]
@VisualBean 
If you wanna use DockStation all your containers will be linked by default.
If you work with Docker via terminal you should use `--link` option.
Also you can check my Docker WP config.
https://github.com/igor-lemon/docker_wordpress_stacksight

**Comment by bit0rez** [comment]
Hi! :)
Can i add my 5 cents to your discussion?
If you are using [User Defined Network](https://docs.docker.com/engine/userguide/networking/#user-defined-networks) you shoud not need to use link. All containers will resolves by name or network alias using [Embedded DNS](https://docs.docker.com/engine/userguide/networking/configure-dns/).
Links uses in Docker's default bridge network.
So if you use docker-compose, it creates UDN for your project containers by default. :)
And DockStation use docker-compose. :)
