### ISSUE TITLE
How to enable system 'HTTP services' on Linux

### ISSUE THREAD

**Issue by woutervddn** [DockStation/dockstation#42]
Dockstation can't find any HTTP services. I'm coming up empty on Google and the website to figure out which services are supported. I just installed Apache, in hopes that would work, but no success.

Which HTTP services are supported in Ubuntu?

**Comment by igor-lemon** [comment]
Hi @woutervddn The app trying to find any service with exposed web ports ('80', '8000', '8080', etc...). But often services has different ports and DockStation can't detect it automatically. For that you can set the service manually. Need to select service that provides HTTP server, like Apache, NGINX, NodeJS HTTP, ...
![image](https://user-images.githubusercontent.com/14764799/28111909-c93c143c-66ff-11e7-8897-1ae38d912ae2.png)
![image](https://user-images.githubusercontent.com/14764799/28112063-583c1768-6700-11e7-85bf-9390d9be7446.png)

**Comment by woutervddn** [comment]
Oh god, I had it the other way around. I thought it needed a webserver on the host to set the hostname, but it just overrides the /etc/hosts file...

Thanks for the clarification, this makes so much more sense now... :)

**Comment by igor-lemon** [comment]
You're welcome :)
