### ISSUE TITLE
In Ubuntu message : "docker is not runing, please run docker and docker compose"

### ISSUE THREAD

**Issue by nikoz84** [DockStation/dockstation#45]
Hello friends its a great idea and congratulation for this contribution, i try to run the dockerstation, but start with this message:

"Docker is not runing, please run docker and docker compose"

i run docker command line without sudo user with success: 

- docker --version 
$ Docker version 17.05.0-ce, build 89658be
- docker run hello-world
- docker ps -a
$ CONTAINER ID IMAGE COMMAND ...
- docker-compose up
$ Creating helloworld_my-test_1 ....
- docker-compose -v
$ docker-compose version 1.11.2 build dfed245
- sudo service docker restart 

who know something about this?

[http://imgur.com/gqQ9Nz5](url)

**Comment by igor-lemon** [comment]
Hi @nikoz84. Did you check issue #18 ?

**Comment by igor-lemon** [comment]
@nikoz84 Is the issue actual?
