### ISSUE TITLE
Unable to find the license in readme or web

### ISSUE THREAD

**Issue by marcbria** [DockStation/dockstation#46]
Hi,
I can't find the license of this development, neither in the readme, nor in the web.
Please, publish it somewhere that could be easy to see.
Thanks a lot in advance,
m.

**Comment by igor-lemon** [comment]
Hi @marcbria we'll publish license and agreement soon.

**Comment by marcbria** [comment]
Thanks. Any clue about the type of license? Free or closed one?

**Comment by igor-lemon** [comment]
@marcbria All versions is free for personal and commercial uses.

**Comment by igor-lemon** [comment]
@marcbria Added the Apache 2.0 license.
