### ISSUE TITLE
Dockstation doesn't work with docker-compose.override.yml

### ISSUE THREAD

**Issue by imilyukov** [DockStation/dockstation#48]
I have projects with docker-compose.yml for common and docker-compose.override.yml for custom environments. When I open my project via Dockstation in there creates containers from docker-compose.yml only.

Could you fix that and what about working with extends and custom yml-file for docker-compose? 

Best regards,

**Comment by igor-lemon** [comment]
Hi @imilyukov 
Duplicate #47 

Yes, we'll fix that.
