### ISSUE TITLE
tried to run alpine test

### ISSUE THREAD

**Issue by Dmitry1987** [DockStation/dockstation#5]
I tried to run regular "docker run alpine 'sleep 1000' "  in 'new project',
but on "start" got this: 

![image](https://cloud.githubusercontent.com/assets/9369080/25951748/467e5d34-3667-11e7-9c68-d6250a8de97c.png)

and on 2nd attempt got this 

![image](https://cloud.githubusercontent.com/assets/9369080/25951765/537f8170-3667-11e7-882c-a002e53efc2d.png)

just FYI (i have no idea what is it).  =)

**Comment by pashist** [comment]
Hi @Dmitry1987 !
Thank you for feedback. Could you check if command `docker run alpine 'sleep 1000' ` works for you from cli ?

**Comment by Dmitry1987** [comment]
correct :)  it's a bad command syntax...
this worked  ```docker run alpine env```
