### ISSUE TITLE
Can't pick image version to pull.

### ISSUE THREAD

**Issue by GeorgSteyn** [DockStation/dockstation#53]
In my case, I want to create a container with the Odoo Version 8.
Currently, I only can add the latest version of an image.
Is there a way to select a different version.

**Comment by igor-lemon** [comment]
Hi @GeorgSteyn. Do you sure that you use official version. Because I have a full list of versions.

![image](https://user-images.githubusercontent.com/14764799/30167762-1a3275da-93f0-11e7-8b20-46090acba1c6.png)

**Comment by GeorgSteyn** [comment]
@igor-lemon 
Thank You for the quick response. I did not know that was possible.
Can there maybe an option at pull to select version?

Because currently, I start to pull then cancel it. Then select the version.

**Comment by igor-lemon** [comment]
Huh. What is image name?
Is it [https://hub.docker.com/_/odoo/](https://hub.docker.com/_/odoo/) ?

I think that it doesn't have any relations with cancel of pulling image. Because info about versions gets from Docker Hub via image name, that gets from compose config.

**Comment by GeorgSteyn** [comment]
Sorry, maybe I must rewind a little.
I create a new project => Then in the Scheme view. I drag and drop any image of any DockerHub repo and DockStation automatically pulls the latest version.

In my case wanting an older version of the image. I must start the pull of the image => Then cancel the pull and then change the version of the container image.

This is the current method I am using after you have shown me you can change the version.

Maybe I am using your tool wrong or this is a feature that needs to be added.
The feature being, when you are requesting to pull any image to first ask for which version to pull.

**Comment by igor-lemon** [comment]
I understand. Yes, it has sense.
