### ISSUE TITLE
Override docker compose config bug

### ISSUE THREAD

**Issue by brunogoossens** [DockStation/dockstation#56]
When I add my docker-compose.dev.yml file as a override docker compose config, he containers are still started with the command
`$ docker-compose up -d`
instead of
`$ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d`

**Comment by igor-lemon** [comment]
Hi @brunogoossens. Why do you think so run `docker-compose up -d` instead `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d` ?
I checked twice and had success result.

**Comment by brunogoossens** [comment]
Ok it does work! My container was a bit slow starting up and that is why I made an incorrect conclusion. 
Maybe the interface was a bit confusing (see screenshot)
<img width="1229" alt="screen shot 2017-09-13 at 12 15 51" src="https://user-images.githubusercontent.com/1636664/30372206-61ecb264-987d-11e7-8312-159cd8b0ff68.png">


The tool is getting really nice! Good work!

**Comment by igor-lemon** [comment]
Huh, I thought that the reason in the header of the modal window.
I think that we'll replace with a full command like as `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d` or will change to some simple `Starting...`.
Cool, thank you for feedback. 👍
