### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by jleni** [DockStation/dockstation#57]
At start I receive an error saying "Docker Compose Error. Docker Compose not installed" I am using:

docker-compose version 1.16.1, build 6d1ac219

And it seems to work well. DockStation also works well with docker and can even show containers that I have started with Docker Compose from the command line.

**Comment by Inlustra** [comment]
I get the same issue! 

 ~  docker-compose version
docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

OS: Ubuntu Gnome 16.10

**Comment by igor-lemon** [comment]
Hi @jleni. Did you check?
https://github.com/DockStation/dockstation/issues/18

**Comment by jleni** [comment]
Yes,
`docker run hello-world
`
runs well. I am using also docker-compose without problems.

**Comment by igor-lemon** [comment]
@jleni Huh. It's very strange. What is OS ?

**Comment by pashist** [comment]
@jleni @Inlustra where is placed your docker-compose binary ?

**Comment by jleni** [comment]
I am using Ubuntu 16.04 LTS

```
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
``` 

the location could be the problem... 
It is placed inside a python virtual environment (conda) ...

```
which docker-compose
/home/lenij/anaconda3/bin/docker-compose
```

**Comment by pashist** [comment]
@jleni you can try to add directory, where docker-compose located, to PATH variable

**Comment by jleni** [comment]
Anaconda (a python distribution) was in the path, however, when it gets installed, it adds itself only to .bashrc

If you run dockstation using a launcher (not from a terminal) the path is not set. The solution is to be sure that you have docker-compose also in .profile.

**Comment by shmidtelson** [comment]
1.5.1 same problem

**Comment by Polytehnitis** [comment]
1.5.1 same problem. please reopen the issue.

**Comment by igor-lemon** [comment]
https://github.com/DockStation/dockstation/issues/288
