### ISSUE TITLE
feature request: image layers window hide

### ISSUE THREAD

**Issue by Dmitry1987** [DockStation/dockstation#6]
some feedback for this window:

![image](https://cloud.githubusercontent.com/assets/9369080/25952392/3769f842-3669-11e7-8a91-4ed2de640246.png)

it's really cool, but blocking.  I think users would prefer to be able hide it (the "OK" was not hiding it in my case - don't know if it should?)

**Comment by Dmitry1987** [comment]
also the size of total image download is not shown, it might be good to add (in header for example)

**Comment by igor-lemon** [comment]
@Dmitry1987 Yep. We'll add function for download image in background mode also will add cancel of downloading.
