### ISSUE TITLE
Custom arguments

### ISSUE THREAD

**Issue by igor-lemon** [DockStation/dockstation#60]
Add project settings for adding custom arguments to `docker-compose` command.

**Comment by bartolomeo88** [comment]
Custom arguments in project doesn't work, result is:
'no such service: -d 
child process exited with code 1'

For replicate the scenario:
- MacOS with Docker Desktop
- Docker container: laradock (https://laradock.io)
- Compose options: nginx mariadb

**Comment by igor-lemon** [comment]
What are arguments was set?

**Comment by bartolomeo88** [comment]
<img width="945" alt="Schermata 2019-06-13 alle 14 31 45" src="https://user-images.githubusercontent.com/51786156/59432630-11ad2600-8de8-11e9-8d64-6d23f0ef540a.png">

**Comment by igor-lemon** [comment]
Huh :D
Where did you found this option?
https://docs.docker.com/compose/reference/overview/
or type `docker-compose --help` for show available options.
