### ISSUE TITLE
Unable to find shell

### ISSUE THREAD

**Issue by jleni** [DockStation/dockstation#61]
Clicking the exec buttons in a containers opens a terminal saying:

Unable to find a shell

I have tried to change between `bash` and `sh` a few times but it does not work.
Is there a configuration file or some other setting that I need to change?
Thanks! I really like dockstation

**Comment by igor-lemon** [comment]
Hi @jleni. Is docker image public? I wanna try to check it with your Docker Image.

**Comment by jleni** [comment]
Yes, official ubuntu
https://hub.docker.com/r/library/ubuntu/

The only change I made is to add a command
`sleep infinity
`

I can log in from a terminal
`docker exec -it ubuntuclean_ubuntu_1 bash
`

but I cant by clicking

**Comment by igor-lemon** [comment]
What is your OS?

**Comment by jleni** [comment]
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by igor-lemon** [comment]
Can you try to catch a terminal window with calling command?
![image](https://user-images.githubusercontent.com/14764799/30638989-e810c4ce-9e05-11e7-9bcf-c878ecc69fe7.png)

**Comment by igor-lemon** [comment]
Also do you use the native Docker or Docker Machine?

**Comment by igor-lemon** [comment]
So. I think that we found a reason.
Please, check your `/usr/bin/x-terminal-emulator`, on which binary file it refers?
https://github.com/linuxmint/cinnamon-spices-applets/issues/840

**Comment by jleni** [comment]
I am using docker.
Yes, I use Terminator. It is likely that is the problem then.
I will check when I get home and report you back.
Thanks

**Comment by jleni** [comment]
So reading the issue you posted it seems more related to an issue in Terminator than in cinnamon spices.
Maybe the Terminator guys already have a workaround or I can try to use a different terminal for docker compose. I would still like to keep Terminator as my default terminal for all other purposes.

**Comment by jleni** [comment]
I meant for dockstation

**Comment by igor-lemon** [comment]
Exactly.
Ok, I'm waiting for news.

**Comment by jleni** [comment]
well..  the /usr/bin/x-terminal-emulator is replaced by a 136 lines python script from terminator. I guess that unless you provide an option to customize the shell calls, this will get more difficult to fix.

By the way, are you planning to open source the code or this project will be closed source?
I would be happy to contribute with a fix to my problem

**Comment by jleni** [comment]
I really like what you've done already, I find it very useful.
I am not super keen on closed source software, though, I understand your point.

**Comment by igor-lemon** [comment]
Thank you for feedback.

**Comment by jleni** [comment]
I hope you are lucky because I like it and with a couple of additional features I would be glad to pay for it

**Comment by igor-lemon** [comment]
@jleni you can write me (email in the GitHub profile) for discussion about it.

**Comment by jleni** [comment]
sorry to disappoint you but I really meant as a product... I did not mean buying the project.. Hopefully but find a way to monetize it.

**Comment by igor-lemon** [comment]
I didn't mean buying the project. I wrote about custom development. Maybe you need some custom functions. We can develop it personally for you. :)

**Comment by igor-lemon** [comment]
@jleni Can I close the issue?

**Comment by jleni** [comment]
Yes, no problem. It seems that it is because of my setup. Thanks!
