### ISSUE TITLE
Docker events. Init error

### ISSUE THREAD

**Issue by Assimilationstheorie** [DockStation/dockstation#64]
Hello.

"Failed to attach docker event listener: Error: connect EACCES /var/run/docker.sock" on Ubuntu

Why?

**Comment by Assimilationstheorie** [comment]
solved: Wrong permissions.

**Comment by scheepers** [comment]
Wrong permissions on what???

**Comment by igor-lemon** [comment]
@scheepers Permissions to docker socket. 
More info
https://docs.docker.com/engine/install/linux-postinstall/
