### ISSUE TITLE
AWS Socket Connection Issue

### ISSUE THREAD

**Issue by jwashington104** [DockStation/dockstation#65]
Hi there, 

I've been trying to connect to my container instances which are running docker 17.03.2-ce. Connecting via SSH using a key is ok, however Dockstation cannot access the socket. 

EDIT: Probably would help if I mentioned I'm using AWS ECS to host my containers.

I just get this:
![screen shot 2017-09-22 at 11 50 36](https://user-images.githubusercontent.com/32195417/30741484-da8eae28-9f8c-11e7-9476-6e95a124edc0.png)
Any ideas?

**Comment by igor-lemon** [comment]
Hi @jwashington104. 
Can you make the tunnel to a local port via terminal?
http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-ssh-tunnel-local.html

**Comment by jwashington104** [comment]
I can certainly try.

Kindest regards,

James Washington
Systems Administrator
ScholarPack

support@scholarpack.com |  www.scholarpack.com
Sales: 01522 716048 <//01522 716048> | Support: 01522 716049 <//01522
716049> | Accounts: 01386 424999

On 22 September 2017 at 12:07:34, Igor Kozlovsky (notifications@github.com)
wrote:

Hi @jwashington104 <https://github.com/jwashington104>.
Can you make the tunnel to a local port via terminal?
http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-ssh-tunnel-local.html

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DockStation/dockstation/issues/65#issuecomment-331418570>,
or mute the thread

**Comment by igor-lemon** [comment]
Ok. I'll be waiting for your result.

**Comment by jwashington104** [comment]
So the tunnel works, I can open one to a local file or to a port but I don't think anything can read the remote socket apart from the running process on the EC2 instance. So I've tried adding users to the docker group on my AWS instance to no avail, I think AWS has this locked down pretty tight.

**Comment by igor-lemon** [comment]
So we have the same trouble. We'll try to find some solutions.
But if you need it urgently you can make it via native way. Open a secure port on the AWS side.
https://docs.docker.com/engine/security/https/
It should work via Plain connection type.
![image](https://user-images.githubusercontent.com/14764799/30745385-8b08cede-9fae-11e7-8fed-b4d28ce70e79.png)

**Comment by jwashington104** [comment]
Thanks for the help! I'll give this a try.

**Comment by igor-lemon** [comment]
Keep in touch. A bit later I'll post here news about SSH + AWS.

**Comment by igor-lemon** [comment]
So, we upped a new AWS instance, EC2 on Ubuntu and had success connection via SSH.
![image](https://user-images.githubusercontent.com/14764799/30749504-4634ac20-9fbc-11e7-9bb6-45f582ba4fb3.png)

Try to up tunnel like this

`ssh user@aws_ip -i ~/path/key.pem -L127.0.0.1:8190:/var/run/docker.sock`

and then exec any docker command via the created tunnel, for example

`docker -H 127.0.0.1:8190 ps`

**Comment by igor-lemon** [comment]
So, is it still actually?

**Comment by jwashington104** [comment]
@igor-lemon, apologies for the lack of an update I've had to put this on a back burner for the moment - hopefully I'll have some time to return to it this week. I'll keep you updated.

**Comment by jwashington104** [comment]
Apologies for the lack of a response. Looking through the responses you've written, I've attempted this myself to no avail. I think it's partly because of the way I'm running the containers, I'm using ECS rather than EC2, the EC2 instances running docker are heavily locked down so I can't set the right permissions to be able to connect to the docker socket. I'll try making the docker instance available over HTTPS and see if that does the trick.

**Comment by igor-lemon** [comment]
So, it's sad. Ok, I'll be waiting for new info.

**Comment by igor-lemon** [comment]
No additional info...

**Comment by jamesprattok** [comment]
I am having this same issue. I created an SSH tunnel but am getting this error.
![Screen Shot 2019-05-22 at 10 18 04 PM](https://user-images.githubusercontent.com/50564422/58223506-8efce380-7cdf-11e9-82ed-d3aea8020a19.png)
