### ISSUE TITLE
Is there a way to rebuild local docker images?

### ISSUE THREAD

**Issue by moneydance** [DockStation/dockstation#67]
If I run docker-compose build from the command line the newly built images aren't used.

**Comment by igor-lemon** [comment]
How this question related with the DockStation app?

**Comment by moneydance** [comment]
When I make a change that would cause a local image to be rebuilt, like changing my npm dependencies, DockStation does not rebuild the image. If I rebuild the image from the command line using docker-compose build, the newly rebuilt image does not replace the old image dockStation was using. If I delete my local image and run the project dockStation will rebuild it and everything works as expected, but its a pain to delete the image every time I need it to be rebuilt.

**Comment by igor-lemon** [comment]
Ok. I'll check that.

**Comment by igor-lemon** [comment]
So, I couldn't repeat your problem. I tried rebuild image from Terminal and after restart application got the latest version of an image.
I can add "Rebuild" button but I'm not sure that it will resolve the issue. Need to find a reason.

**Comment by MrCroft** [comment]
In my case, if I rebuild the image myself from the command line, it does pick it up.
But if I simply make some changes to the Dockerfile, then DockStation doesn't rebuild the image. It simply starts the one that's already created.

**Comment by igor-lemon** [comment]
@MrCroft It's not difficult. We'll add the "Rebuild" button.
