### ISSUE TITLE
Option to specify custom docker-compose.yml name

### ISSUE THREAD

**Issue by sergeymakinen** [DockStation/dockstation#68]
Subj. As we use different names (`-f` parameter), the option will make it possible to use DockStation. :)

Offtopic: thanks for the great product and good luck!

**Comment by igor-lemon** [comment]
Hi @sergeymakinen. Thanks for feedback
We chose a way that the main config should have `docker-compose.yml` name, but override configs you can name differently. We'll discuss your proposition.

**Comment by sergeymakinen** [comment]
Nope… ATM I use DS as a GUI for running containers and manage starting/stopping in a CLI.
