### ISSUE TITLE
Error when creating manual connection on 127.0.0.1

### ISSUE THREAD

**Issue by wesleylancel** [DockStation/dockstation#69]
I'm trying to add a Docker instance that is available on 127.0.0.1:2375 (but it's not managed through either Docker for Mac or docker-machine), but there's an error message below the IP saying "Local IP added for default connection.".

**Comment by igor-lemon** [comment]
Hi @wesleylancel 
Doh. Yep, we made a validation for unique IP.
So, I think that we'll remake "Connection manager" also we'll looking some additional ways for working with local Docker.

**Comment by igor-lemon** [comment]
So. We found a solution and we'll publish it into a next release.
Right now you can make a bit lifehack.
Export your settings
![image](https://user-images.githubusercontent.com/14764799/30960426-a36133f8-a44b-11e7-9294-3f92061b59ed.png)
Then unzip the settings file, open the settings file via any text editor. And change `connections` object. Add into this object next
```json
{"name":"Local Docker","ip":"127.0.0.1","port":2375,"more13":true,"certificate_ca":"","certificate":"","certificate_pk":"","type":"plain","key":"ab85c785-1771-4a09-826f-7f12477ccd7d"}
```
Then save changes. Zip the changed settings file and import settings into app.
![image](https://user-images.githubusercontent.com/14764799/30960676-692c6774-a44c-11e7-96b2-d0033ffb61ff.png)

**Comment by wesleylancel** [comment]
Thanks for finding a solution! Though I don't seem to have that option in my menu bar, just has one label "Dockstation" with a "Quit" item in it.

**Comment by igor-lemon** [comment]
Hm... What is your OS?

**Comment by wesleylancel** [comment]
macOS Sierra

**Comment by igor-lemon** [comment]
Checked. You're right. The menu will load after Docker inits. We'll fix that bug too.
Ok. Your config file is located `~/Library/Application Support/dockstation/Settings`.
You can do it manually. But before, I advise to make a backup of the Settings file.

**Comment by wesleylancel** [comment]
Thanks! It now connects to the Docker instance and shows all my containers in the "Containers" tab. Only thing that doesn't seem to be working yet is the "Projects"-tab, but that's probably related to no Docker being initialized?

**Comment by igor-lemon** [comment]
Unfortunately, you can't work with Projects right now because for working with Project need to init `local connection`. Right now you connected like as `remote connection`.
We'll add options to preferences of the app for set `init local connection`, where you can set your connection as default.

**Comment by wesleylancel** [comment]
Great, thanks, will wait for that!
