### ISSUE TITLE
Unable to add hosts by domain name

### ISSUE THREAD

**Issue by jenssegers** [DockStation/dockstation#75]
The validation on the IP input field only allows IPs and not domain names. I have host running behind elastic IPs so I kind of want to use their domain name rather than a static IP.

**Comment by igor-lemon** [comment]
Hi @jenssegers . Ok. We'll add this in the next 1.4 release.

**Comment by wouterds** [comment]
Couldn't agree more with @jenssegers, looking forward to the update @igor-lemon!
