### ISSUE TITLE
Renamed directory with project - how do i edit the project to point to the new path?

### ISSUE THREAD

**Issue by Moulde** [DockStation/dockstation#77]
I'm getting an error that the project directory does not exist, and that the docker-compose file is not writeable.

The GUI doesnt seem like it allows to edit the path.
Can i edit a project file somewhere instead?

**Comment by igor-lemon** [comment]
Hi @Moulde 
You can remove the project from the app and re-add a project with a new path.

**Comment by igor-lemon** [comment]
@Moulde 
So, we'll add a possibility to change a path of a moved project.
