### ISSUE TITLE
"Exec" button don't work

### ISSUE THREAD

**Issue by MyrikLD** [DockStation/dockstation#78]
OS: Manjaro 17.0.5
Please, make row, where I can set command or path for my terminal emulator. On my OS your "Exec" button dont work.

**Comment by igor-lemon** [comment]
Hi @MyrikLD 
ok

**Comment by konstantingoretzki** [comment]
Same problem for me with Antergos.

**Comment by MyrikLD** [comment]
add file in /bin with name x-terminal-emulator
then run:
echo '#!/bin/bash
/usr/bin/xterm -hold -e ~/ "$*"' > /bin/x-terminal-emulator

**Comment by igor-lemon** [comment]
@MyrikLD Thanks. We're testing final v1.4 where we added a param to set a custom terminal emulator.
