### ISSUE TITLE
CANT USE  on CENTOS 7

### ISSUE THREAD

**Issue by gudge25** [DockStation/dockstation#82]
[root@localhost src]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@localhost src]# ./dockstation-1.3.0-x86_64.AppImage
which: no desktop-file-validate in (/tmp/.mount_HehQhL/usr/bin:/tmp/.mount_HehQhL/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
desktop-file-validate is missing. Skipping /tmp/.mount_HehQhL/AppRun.
[root@localhost src]#

**Comment by igor-lemon** [comment]
Hi @gudge25. Hm, I'll check. Thanks for the issue.

**Comment by robertcristensen** [comment]
Hi. 
Trying to make it work on Centos 7.
After installing dependencies it doesn't show errors any more. But after running image it seems nothing happens:
./dockstation-1.3.0-x86_64.AppImage

**Comment by igor-lemon** [comment]
Please try again
