### ISSUE TITLE
Add capability to edit/add environment variable

### ISSUE THREAD

**Issue by ramabmtr** [DockStation/dockstation#83]
As long as I see, edit environment variable can perform on the project tab, but we can edit/add environment variable on the container tab. It would be nice if we also can edit/add env var in a single container too. Even better if we can run an image directly from dockstation too.

for now I manually run my docker image from terminal if I want to edit/add env var

**Comment by igor-lemon** [comment]
We don't work with independent containers. We work with Docker Compose. 
You can configure needed ENV params here and after restart project, compose will recreate a container with that params.
![image](https://user-images.githubusercontent.com/14764799/32215393-e9c539d8-be32-11e7-856d-8ef1b9540453.png)

**Comment by ramabmtr** [comment]
So, it mean dockstation will not support configure env for single container? or it'll be supported on next version (maybe) ?

**Comment by igor-lemon** [comment]
No. We will not support work with single containers because it not has any sense because you can do it via Compose. If you don't want to work with Compose you can use some other app like as Kitematic, Portainer, Shipyard.

**Comment by ramabmtr** [comment]
Ok, thanks @igor-lemon , will give a try for this app, this is really nice app btw, I like the UI very much.
I'll close this issue since it not relevant to this app design
