### ISSUE TITLE
GUI slows very much on opening containers with malformed logs

### ISSUE THREAD

**Issue by nevitas** [DockStation/dockstation#84]
Some of my containers have corrupted (or malformed) logs — see picture below.

![image](https://user-images.githubusercontent.com/5923148/32267268-b9b26878-befb-11e7-9eee-0fa3d8153f68.png)

And DockStation slows very much when I click on such container — see picture  below. GUI just hangs for 5-15 seconds. And the CPU is running hot. 

Containers which have normal logs open instantly.

**Comment by igor-lemon** [comment]
What do you have in Terminal if you run `docker-compose logs -f` ?

**Comment by nevitas** [comment]
Sorry but I've already deleted that container with malformed logs.
