### ISSUE TITLE
Init Error: Failed to attach docker event listener on startup

### ISSUE THREAD

**Issue by starsoccer** [DockStation/dockstation#86]
When starting DockStation I get the error, Init Error: Failed to attach docker event listener: Error: connect ENOENT //./pipe/docker_engine

On windows 10 64bit fall creators update

**Comment by igor-lemon** [comment]
Hi @starsoccer Did you have running Docker?

**Comment by starsoccer** [comment]
No, that fixed it. You really should clarify that. I had assumed DockStation would start if it wasnt running.
