### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by LouWii** [DockStation/dockstation#9]
Hi there,

Dockstation really looks awesome. 

Since a lot of people are using Docker on remote servers, I was wondering if you are planning to add a remote feature, where the app would connect through SSH to retrieve Docker data. That would be a killer feature.

Thanks for all the work !

**Comment by igor-lemon** [comment]
Hi. Thank you for feedback.
It's awesome because we have plans to release it feature. :)
We'll do that but a bit later because right now we have a plan of works for the next 1.5-2 months.

**Comment by LouWii** [comment]
Cool, let me know when it's all done :)

**Comment by igor-lemon** [comment]
Ok. 👍

**Comment by igor-lemon** [comment]
@LouWii is Done. We released it on Containers tab. Later will doing it for projects too. But for that will up a new issue.

**Comment by LouWii** [comment]
Thanks a lot for adding this. I tried this today, and I have a question.

I'm using an ssh key to connect to my server, but not with root (as it's not recommended for security reasons). My user can have root privileges using `sudo` once connected to the server.

I believe the remote access only works with a `root` connection ? The app correctly connects to the server, but then I got a "Could not connect to remote docker: socket hang up". Docker is correctly running on my server, my site running on docker is accessible. So I guess the app can't connect to the socket because the user doesn't have the right privileges.

**Comment by igor-lemon** [comment]
@LouWii Hi. Root user not required, your user must have access to /var/run/docker.sock. Because app need access to the socket for make forwarding. If you don't have socket access or don't wanna change permissions you can bind docker to port and make certificates auth (we support it type too).
For that way you can read info here:
https://docs.docker.com/engine/security/https/
