### ISSUE TITLE
[tooltip] "Dockerfile seems to be invalid" although it is in fact valid

### ISSUE THREAD

**Issue by MrCroft** [DockStation/dockstation#90]
For any of the `Dockerfile` files in my project, even for the simplest one, such as:
```
FROM nginx:latest
```
if I go into the **SCHEME** view and hover over the small _Info_ icon next to the word _Dockerfile_, a tooltip appears saying: _**Dockerfile seems to be invalid**_

DockerStation version: 1.3.0
Docker for Windows: 17.09.0-ce, build afdb6d4
OS: Windows 10 PRO (1709)

![image](https://user-images.githubusercontent.com/2809154/33151934-d5dc186c-cfe2-11e7-93dc-27a2c97390f3.png)

**Comment by igor-lemon** [comment]
So. I don't understand the issue :)
What is problem?

**Comment by MrCroft** [comment]
My point is that I think the tooltip is wrong. I'm no docker expert, but I think that the Dockerfile is actually valid.
