### ISSUE TITLE
Improve performance for container log view

### ISSUE THREAD

**Issue by af6140** [DockStation/dockstation#96]
The container log view sometimes is quite slow and can freeze app for some time. Need to  improve performance.

This can be either limit log lines or since/timestamp.

**Comment by igor-lemon** [comment]
Hi @af6140. Is it freeze on containers with a big list of logs?

**Comment by darrencrossley** [comment]
As far as I can see #7 was never resolved - the logs view doesn't reconnect if the container is restarted. Not sure if this is related to @af6140 but the only way I've found to reconnect it to switch to a different view and back.

Performance is also often not great compared to the terminal and suffers when given large amounts of log data.

**Comment by igor-lemon** [comment]
@darrencrossley Can you explain what's wrong? Because I can't understand what is problems. Logs show & refresh correctly. How to reproduce your problem?

Sure it not fast like Terminal because the app gets up a process and retranslate logs into container window.

**Comment by af6140** [comment]
I am wondering we can add configuration like only show last N lines of log, so at least we can control how much info get loaded. docker logs does have this option.

**Comment by af6140** [comment]
@darrencrossley , from my experience, seems that when container restarted, it takes a while for the new log to show up.

**Comment by hsluoyz** [comment]
Will this issue be fixed? I tried to run the image: https://hub.docker.com/r/projectunik/compilers-rump-go-hw/, but the log is too slow to bear.

**Comment by igor-lemon** [comment]
@hsluoyz Yes. We'll add an option into the app where you can set a count of lines. The app shows last 1000 lines now.
