### ISSUE TITLE
MAC - Failed to fetch container logs

### ISSUE THREAD

**Issue by squishydale** [DockStation/dockstation#97]
Guys, this is an awesome project.  Thanks for this.

I have everything up and working in Ubuntu 16.04 flawlessly.  I'm testing it in other OS's and in Mac OS Sierra, I can get most everything working, but the LOGS tab gives me this any container I've created:

> Failed to fetch container logs

Is there a setting I'm supposed to be putting in for dockerstation to see the container logs?

**Comment by igor-lemon** [comment]
Hi @squishydale. Are containers running?
Also what is Docker version?

**Comment by squishydale** [comment]
Hey @igor-lemon 
The containers are all running like they should be.  I have access to their command terminals and everything like that, and they are responding on the ports that I've exported.

All of this software has been downloaded and installed today, so I'm running: 

Docker Community Edition for Mac - Version 17.11.0-ce, build 1caf76c
I've had the issue with both the Stable build and the Edge build

I'm running Dockstation v1.3.0

**Comment by igor-lemon** [comment]
Hm... I can't to reproduce your issue.
So maybe can you give me your compose config?

**Comment by squishydale** [comment]
I tried with both a pre-built docker-compose file as well as just dragging and dropping servers in the scheme and had the same result.  I'm currently doing a complete software re-install to try to rule out an issue with this particular machine.

**Comment by squishydale** [comment]
https://drive.google.com/file/d/16MWNZ2MO2TJuV1pgGLEvF5mATc_qOp3n/view?usp=sharing

I just did a full wipe / reinstall of OSX, with a fresh install of docker and dockstation.
macOS Sierra - Version 10.12.6
Docker version 17.09.1-ce, build 19e2cf6
Dockstation - v1.3.0

I'm attaching the docker-compose.yml (renamed for attachment)
[docker-compose.txt](https://github.com/DockStation/dockstation/files/1548322/docker-compose.txt)

**Comment by igor-lemon** [comment]
@squishydale Hi. We reproduced the trouble. It happed after change settings without restart of a container. So, we'll fix it.
